version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hc
    expose:
       - 5432
    ports:
       - 5432:5432      
  health_check:
        environment:
          - DATABASE=db
        restart: always
        build:
            context: .
            dockerfile: ./docker/healthcheck
        command: "python3 start.py --type asynq --urls 'http://ya.ru' 'http://mail.ru' 'http://cb-ideas.com' 'http://cb-ideas.ru' 'http://cb-ideas.rut' 'http://google.com' 'http://vk.com'  --interval 2 --concurrency 3 --timeout 1"
        depends_on:
            - db    
  get_status:
        environment:
          - DATABASE=db
        restart: always
        build:
            context: .
            dockerfile: ./docker/healthcheck
        expose:
          - 8000
        ports:
          - 8000:8000      
        command: "gunicorn -w 3 -b 0.0.0.0:8000 services.get_status:app"
        depends_on:
            - db    
